version: '3.1'

services:

  backend:
    build:
      context: '.'
      dockerfile: './.docker/Dockerfile'
    volumes:
      - .:/app
    command: ["flask", "run", "--host", "0.0.0.0"]
    ports:
      - "8082:5000"