"""add unique key and constrain for email and uuid

Revision ID: 01870fc642ac
Revises: c5da394a5927
Create Date: 2020-01-11 22:02:25.116298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01870fc642ac'
down_revision = 'c5da394a5927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_password_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_password_hash')
    # ### end Alembic commands ###
