"""add signatory

Revision ID: 1b31f9525c88
Revises: 9883397625eb
Create Date: 2020-03-08 19:17:44.137748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b31f9525c88'
down_revision = '9883397625eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disbursments', sa.Column('signatory', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disbursments', 'signatory')
    # ### end Alembic commands ###
