"""Add status field in user

Revision ID: 20648f384068
Revises: 9a36a5a3054c
Create Date: 2020-01-16 23:00:53.759797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20648f384068'
down_revision = '9a36a5a3054c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    # ### end Alembic commands ###
