"""fix duplicate and add audit fields in member schema

Revision ID: 245fdf885096
Revises: 44c434b2a066
Create Date: 2020-01-22 15:43:39.479242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '245fdf885096'
down_revision = '44c434b2a066'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('created_at', sa.DATETIME(), nullable=False))
    op.add_column('members', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('members', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    op.add_column('members', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'members', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key(None, 'members', 'users', ['updated_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.drop_column('members', 'updated_by_id')
    op.drop_column('members', 'updated_at')
    op.drop_column('members', 'created_by_id')
    op.drop_column('members', 'created_at')
    # ### end Alembic commands ###
