"""add loans table

Revision ID: 2e0c5d2bb364
Revises: 580922b7f9e5
Create Date: 2020-01-12 00:51:28.221857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e0c5d2bb364'
down_revision = '580922b7f9e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=100), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('co_maker_1', sa.Integer(), nullable=False),
    sa.Column('co_maker_2', sa.Integer(), nullable=False),
    sa.Column('loan_amount', sa.Integer(), nullable=False),
    sa.Column('payment_term', sa.Integer(), nullable=False),
    sa.Column('service_charge', sa.Float(), nullable=False),
    sa.Column('interest', sa.Float(), nullable=False),
    sa.Column('capital_build_up', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loans')
    # ### end Alembic commands ###
