"""correct audit fields to members

Revision ID: 3a8b1c83665a
Revises: 245fdf885096
Create Date: 2020-01-23 14:20:40.355679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a8b1c83665a'
down_revision = '245fdf885096'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('created_by_id', sa.Integer(), nullable=False))
    op.add_column('loans', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'loans', 'users', ['updated_by_id'], ['id'])
    op.create_foreign_key(None, 'loans', 'users', ['created_by_id'], ['id'])
    op.drop_column('loans', 'updated_by')
    op.drop_column('loans', 'created_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('loans', sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'loans', type_='foreignkey')
    op.drop_constraint(None, 'loans', type_='foreignkey')
    op.drop_column('loans', 'updated_by_id')
    op.drop_column('loans', 'created_by_id')
    # ### end Alembic commands ###
