"""co maker null set to not null

Revision ID: 3d413eedc314
Revises: 7f2fa911e979
Create Date: 2020-01-12 02:29:22.053100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d413eedc314'
down_revision = '7f2fa911e979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('loans', 'co_maker_1',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('loans', 'co_maker_2',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('loans', 'member_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('loans', 'member_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('loans', 'co_maker_2',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('loans', 'co_maker_1',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
