"""add disbursment table

Revision ID: 465fcc5e12d0
Revises: 99e766327847
Create Date: 2020-02-01 21:07:56.024625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '465fcc5e12d0'
down_revision = '99e766327847'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disbursment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=100), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('check_voucher', sa.String(), nullable=False),
    sa.Column('check_number', sa.String(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('disbursment')
    # ### end Alembic commands ###
