"""remove nullify on reciepts loan_id

Revision ID: 5b9f7a66eac9
Revises: bd11181bc7ee
Create Date: 2020-02-07 20:03:06.518829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b9f7a66eac9'
down_revision = 'bd11181bc7ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reciepts', 'loan_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reciepts', 'loan_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
