"""Add additional member and beneficiaries table

Revision ID: 6245efe84d8d
Revises: 3a8b1c83665a
Create Date: 2020-01-23 16:37:58.116666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6245efe84d8d'
down_revision = '3a8b1c83665a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beneficiaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('relationship', sa.String(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('members', sa.Column('monthly_income', sa.String(), nullable=False))
    op.add_column('members', sa.Column('recommended_by', sa.Integer(), nullable=True))
    op.add_column('members', sa.Column('religion', sa.String(), nullable=False))
    op.add_column('members', sa.Column('source_of_income', sa.String(), nullable=False))
    op.add_column('members', sa.Column('spouse_name', sa.String(), nullable=True))
    op.create_foreign_key(None, 'members', 'members', ['recommended_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.drop_column('members', 'spouse_name')
    op.drop_column('members', 'source_of_income')
    op.drop_column('members', 'religion')
    op.drop_column('members', 'recommended_by')
    op.drop_column('members', 'monthly_income')
    op.drop_table('beneficiaries')
    # ### end Alembic commands ###
