"""add foriegn key to loan

Revision ID: 6ac4d30b7563
Revises: 465fcc5e12d0
Create Date: 2020-02-01 21:11:29.954777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ac4d30b7563'
down_revision = '465fcc5e12d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'disbursment', 'loans', ['loan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'disbursment', type_='foreignkey')
    # ### end Alembic commands ###
