"""add foreign key on user

Revision ID: 720c3d2619d9
Revises: bee4776bda21
Create Date: 2020-02-15 00:29:35.907592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '720c3d2619d9'
down_revision = 'bee4776bda21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'users', 'members', ['member_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    # ### end Alembic commands ###
