"""add more relationships to loans

Revision ID: 7f2fa911e979
Revises: f87f622012e3
Create Date: 2020-01-12 02:24:22.506615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f2fa911e979'
down_revision = 'f87f622012e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('loans', 'co_maker_1',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('loans', 'co_maker_2',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'loans', 'members', ['co_maker_1'], ['id'])
    op.create_foreign_key(None, 'loans', 'members', ['co_maker_2'], ['id'])
    op.add_column('users', sa.Column('created_by_id', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['updated_by_id'], ['id'])
    op.create_foreign_key(None, 'users', 'users', ['created_by_id'], ['id'])
    op.drop_column('users', 'updated_by')
    op.drop_column('users', 'created_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'updated_by_id')
    op.drop_column('users', 'created_by_id')
    op.drop_constraint(None, 'loans', type_='foreignkey')
    op.drop_constraint(None, 'loans', type_='foreignkey')
    op.alter_column('loans', 'co_maker_2',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('loans', 'co_maker_1',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
