"""init

Revision ID: 85a77779c175
Revises: 
Create Date: 2020-03-06 17:17:44.325554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85a77779c175'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reciepts', sa.Column('invoice_id', sa.Integer(), nullable=False))
    op.alter_column('reciepts', 'loan_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'reciepts', 'invoices', ['invoice_id'], ['id'])
    op.drop_column('reciepts', 'loan_payment_term')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reciepts', sa.Column('loan_payment_term', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'reciepts', type_='foreignkey')
    op.alter_column('reciepts', 'loan_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('reciepts', 'invoice_id')
    # ### end Alembic commands ###
