"""add status in disbursments

Revision ID: 8a6939fdfa5b
Revises: 071a47a0da41
Create Date: 2020-02-02 17:28:33.574262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a6939fdfa5b'
down_revision = '071a47a0da41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disbursments', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disbursments', 'status')
    # ### end Alembic commands ###
