"""co makers are optional

Revision ID: 99e766327847
Revises: b4eef12a45ba
Create Date: 2020-01-30 19:25:37.553388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99e766327847'
down_revision = 'b4eef12a45ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('loans', 'co_maker_1_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('loans', 'co_maker_2_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('loans', 'co_maker_2_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('loans', 'co_maker_1_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
