"""empty message

Revision ID: 9a36a5a3054c
Revises: a299f931521d
Create Date: 2020-01-16 22:56:14.846507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a36a5a3054c'
down_revision = 'a299f931521d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'users', 'members', ['member_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'created_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
