"""re-organize relationship tables

Revision ID: a299f931521d
Revises: 3d413eedc314
Create Date: 2020-01-12 03:01:01.798171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a299f931521d'
down_revision = '3d413eedc314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('co_maker_1_id', sa.Integer(), nullable=False))
    op.add_column('loans', sa.Column('co_maker_2_id', sa.Integer(), nullable=False))
    op.drop_constraint('FK__loans__co_maker___6166761E', 'loans', type_='foreignkey')
    op.drop_constraint('FK__loans__co_maker___607251E5', 'loans', type_='foreignkey')
    op.create_foreign_key(None, 'loans', 'members', ['co_maker_1_id'], ['id'])
    op.create_foreign_key(None, 'loans', 'members', ['co_maker_2_id'], ['id'])
    op.drop_column('loans', 'co_maker_2')
    op.drop_column('loans', 'co_maker_1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('co_maker_1', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('loans', sa.Column('co_maker_2', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'loans', type_='foreignkey')
    op.drop_constraint(None, 'loans', type_='foreignkey')
    op.create_foreign_key('FK__loans__co_maker___607251E5', 'loans', 'members', ['co_maker_1'], ['id'])
    op.create_foreign_key('FK__loans__co_maker___6166761E', 'loans', 'members', ['co_maker_2'], ['id'])
    op.drop_column('loans', 'co_maker_2_id')
    op.drop_column('loans', 'co_maker_1_id')
    # ### end Alembic commands ###
