"""add issue date

Revision ID: aca039227c56
Revises: 1b31f9525c88
Create Date: 2020-03-08 19:54:49.512641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aca039227c56'
down_revision = '1b31f9525c88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disbursments', sa.Column('issue_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disbursments', 'issue_date')
    # ### end Alembic commands ###
