"""add timestamps

Revision ID: c5da394a5927
Revises: eea0575e01f2
Create Date: 2020-01-11 21:27:43.038614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5da394a5927'
down_revision = 'eea0575e01f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DATETIME(), nullable=False))
    op.add_column('users', sa.Column('created_by', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('updated_by', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_by')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_by')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
