"""add relationship to loans and members

Revision ID: f87f622012e3
Revises: 2e0c5d2bb364
Create Date: 2020-01-12 01:07:23.853223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f87f622012e3'
down_revision = '2e0c5d2bb364'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('loans', 'member_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'loans', 'members', ['member_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'loans', type_='foreignkey')
    op.alter_column('loans', 'member_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
